Repository crc-org/snc, pull requests merged in 2020-11, with the labels that each got.

#260 Add the script run by the CI
  ci.sh
Labels: approved, lgtm

#266 Destroy the cluster at the end of the CI run
  ci.sh
Labels: approved, lgtm

#251 Check if libvirt default network is present for ppc64le
  snc.sh
Labels: approved, lgtm, ok-to-test

#268 Fix stopping of pods
  createdisk.sh
Labels: approved, lgtm

#267 Add bundle name to metadata json
  crc-bundle-info.json.sample
  createdisk.sh
Labels: approved, lgtm

#269 Support building an OKD bundle with the oc binary embedded
  createdisk.sh
  snc.sh
Labels: ok-to-test

#284 Revert "Use unsupported config map to force the cert rotation"
  createdisk.sh
  kubelet-bootstrap-cred-manager-ds.yaml.in
  snc.sh
Labels: approved, do-not-merge/hold
