Repository crc-org/snc, pull requests merged in 2020-07, with the labels that each got.

#196 Add VALID_CERT bool env to validate the cert
  createdisk.sh
Labels: lgtm

#202 Use threads option for xz compression
  createdisk.sh
Labels: lgtm

#201 Use `oc scale` instead of `oc patch` for scaling down ingress controller
  snc.sh
Labels: lgtm

#206 Use raw image on macos
  createdisk.sh
Labels: approved, lgtm

#207 Add more details in the README
  README.md
Labels: approved, lgtm

#208 Revert "Use raw image on macos"
  createdisk.sh
Labels: approved

#209 Enable Multi-Architecture Support
  install-config.yaml
  snc.sh
Labels: approved, do-not-merge/hold, ok-to-test

#213 Update the mirror url to use latest-4.5
  snc.sh
Labels: approved, lgtm

#215 Cleanup packages and vmlinuz/initramfs files after bundle tarball creation
  createdisk.sh
Labels: approved

#217 Disable the network time sync for the bundle
  createdisk.sh
Labels: approved, lgtm

#218 Use jsonpath to get the csr resource name
  snc.sh
Labels: approved, lgtm

#219 Use oc binary from the payload instead user provided
  snc.sh
Labels: approved, lgtm
