Repository crc-org/snc, pull requests merged in 2020-09, with the labels that each got.

#231 Load hv_sock module
  createdisk.sh
Labels: approved, lgtm

#233 Add 5 min timeout for csr request
  snc.sh
Labels: approved

#232 Enable creating SNC for OKD 4
  README.md
  createdisk.sh
  snc.sh
Labels: approved, lgtm, ok-to-test

#240 Add CVO override for cluster-node-tuning
  cvo_override.yaml
  snc.sh
Labels: approved
