Repository crc-org/snc, pull requests merged in 2020-10, with the labels that each got.

#243 Make crc-bundle-info.json the first element in the tar archive
  createdisk.sh
Labels: approved, lgtm

#229 Add auth operator hack to enable single apiserver
  snc.sh
Labels: approved

#245 Switch master to 4.6 candidate release
  snc.sh
Labels: approved, lgtm

#242 Add openshift client oc in the bundle
  .gitignore
  createdisk.sh
  snc.sh
Labels: approved

#247 Add entry in NetworkManager conf to use dnsmasq as dns
  snc.sh
Labels: approved, lgtm

#248 RFC: Optionally add a default pull secret in the bundle
  README.md
  crc-bundle-info.json.sample
  createdisk.sh
Labels: approved, lgtm

#255 Install the unzip package if not present
  snc.sh
Labels: approved, lgtm

#257 Revert "Add CVO override for cluster-node-tuning"
  cvo_override.yaml
  snc.sh
Labels: approved, lgtm

#254 Remove version info from oc binary download
  snc.sh
Labels: approved

#258 Fix error for crictl stopp/rmp pods
  createdisk.sh
Labels: approved, lgtm

#234 Add gvisor-tap-vsock daemon
  createdisk.sh
Labels: approved

#253 shell scripts fail on first error
  crc_libvirt.template
  createdisk.sh
Labels: approved, lgtm

#261 Revert "Tag cluster-kube-apiserver-operator image"
  createdisk.sh
Labels: approved, lgtm

#249 Address Red Hat Support in README
  README.md
Labels: needs-ok-to-test
