Repository crc-org/snc, pull requests merged in 2021-03, with the labels that each got.

#344 Add retry for virsh commands
  tools.sh
Labels: approved

#346 Ignore replica update for etcd-quorum-guard
  snc.sh
Labels: approved, lgtm

#348 Add kubeadmin user as part of htpasswd
  snc.sh
  tools.sh
Labels: approved, lgtm

#349 Use systemd unit file to create dummy network
  createdisk.sh
Labels: approved

#351 Add a check for systemReserved key in kubelet
  createdisk.sh
Labels: approved

#361 Remove `developer` user from sudoer cluster role
  snc.sh
Labels: approved, lgtm

#353 Remove more memory requests (400Mi) and second packageserver container
  snc.sh
Labels: approved, lgtm

#360 Use machineconfig resource to create dummy network service
  99-openshift-machineconfig-master-dummy-networks.yaml
  createdisk.sh
  snc.sh
Labels: approved, lgtm

#368 Add must-gather logs in case openshift-install fails
  snc.sh
Labels: approved

#373 Remove OPENSHIFT_INSTALL_EXPERIMENTAL_CLUSTER_PROFILE env for installer
  snc.sh
Labels: approved, do-not-merge/hold, lgtm

#375 Remove auth and etcd hack
  snc-library.sh
  snc.sh
Labels: approved, lgtm

#364 Add k8s conformance tests for CI
  ci.sh
Labels: approved, do-not-merge/hold, lgtm

#377 Add rsync package to host machine for CI run
  ci.sh
Labels: approved
