Repository crc-org/snc, pull requests merged in 2021-05, with the labels that each got.

#408 Add security message on the web console
  security-notice.yaml
  snc.sh
Labels: approved

#409 Add a tip in login page for getting credentials
  login.html.patch
  oauth_cr.yaml
  snc.sh
  tools.sh
Labels: approved

#404 Add CA cert of exposed registry route to VM
  snc.sh
Labels: approved, do-not-merge/hold, lgtm

#419 Force kill any existing dnf process
  ci.sh
Labels: approved

#415 Remove kubeadmin-passwd file from the bundle
  crc-bundle-info.json.sample
  createdisk-library.sh
  test-metadata-generation.sh
Labels: approved, has-to-be-in-release

#423 Revert "Force kill any existing dnf process"
  ci.sh
Labels: approved

#427 fix hardcoded api.crc.testing
  snc-library.sh
Labels: approved, lgtm, ok-to-test

#418 Externalization VM settings: memory, vCPUs and disk size.
  snc.sh
Labels: approved, lgtm, ok-to-test
