Repository crc-org/snc, pull requests merged in 2022-12, with the labels that each got.

#619 qemu-ga: Remove left-over commented out line
  createdisk-library.sh
Labels: lgtm, approved

#623 build qemu-ga selinux policy package inside the guest
  createdisk-library.sh
Labels: lgtm, approved

#626 qemuga: Ensure selinux policy module is rhel8-compatible
  createdisk-library.sh
Labels: lgtm, approved, do-not-merge/hold

#631 Misc changes for cert approval and validating
  snc-library.sh
Labels: approved

#630 Add retry to get machine config in case apiserver not respond at first
  snc.sh
Labels: approved

#634 [release-4.12] Add retry to get machine config in case apiserver not respond at first
  snc.sh
Labels: lgtm, approved
