Repository crc-org/snc, pull requests merged in 2024-09, with the labels that each got.

#950 tools.sh: increased number of retries
  tools.sh
Labels: lgtm

#934 Delete pods and lease using etcd container
  createdisk.sh
Labels: approved

#960 ci.sh: moved test artifacts folder to crc-tmp-install-data
  ci.sh
Labels: lgtm, approved

#962 ci: update go version from 1.21 to 1.22
  ci.sh
  ci_microshift.sh
Labels: lgtm, approved

#966 Update qemu-user-static-x86 to 8.2.6 version
  createdisk.sh
Labels: lgtm, approved

#972 [OKD] Get the oc tarball for windows using payload
  snc-library.sh
Labels: lgtm, approved
